export enum Type {
  bug = "bug",
  fire = "fire",
  rock = "rock",
  ground = "ground",
  normal = "normal",
  grass = "grass",
  flying = "flying",
  water = "water",
  poison = "foison",
  eletric = "eletric",
  ghost = "ghost",
  fairy = "fairy",
  fighting = "fighting",
  psychic = "psychic",
  steel = "steel",
  ice = "ice",
  dark = "dark",
  dragon = "dragon"
}
