export enum Type {
  Bug = "Bug",
  Fire = "Fire",
  Rock = "Rock",
  Ground = "Ground",
  Normal = "Normal",
  Grass = "Grass",
  Flying = "Flying",
  Water = "Water",
  Poison = "Poison",
  Eletric = "Eletric",
  Ghost = "Ghost",
  Fairy = "Fairy",
  Fighting = "Fighting",
  Psychic = "Psychic",
  Steel = "Steel",
  Ice = "Ice",
  Dark = "Dark",
  Dragon = "Dragon"
}
